CREATE DATABASE IF NOT EXISTS tourism_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tourism_db;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS payments, bookings, rooms, packages, destinations, hotels, drivers, customers, contact_messages, users;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE users (
 user_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL, role ENUM('customer','driver','hotel','admin') NOT NULL DEFAULT 'customer',
 status ENUM('active','inactive','pending','rejected') NOT NULL DEFAULT 'active', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(role,status)
) ENGINE=InnoDB;
CREATE TABLE customers (customer_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL UNIQUE,phone VARCHAR(40) NOT NULL,address TEXT NULL,profile_image VARCHAR(255) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE drivers (driver_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NOT NULL UNIQUE,full_name VARCHAR(120) NOT NULL,phone VARCHAR(40) NOT NULL,license_number VARCHAR(80) NOT NULL UNIQUE,vehicle_type VARCHAR(80) NOT NULL,vehicle_registration VARCHAR(80) NOT NULL,vehicle_capacity TINYINT UNSIGNED NOT NULL,profile_image VARCHAR(255) NULL,availability_status ENUM('Available','Busy','Offline') DEFAULT 'Offline',status ENUM('pending','active','inactive','rejected') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE hotels (hotel_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id INT UNSIGNED NULL UNIQUE,hotel_name VARCHAR(150) NOT NULL,description TEXT NULL,address TEXT NOT NULL,city VARCHAR(100) NOT NULL,phone VARCHAR(40) NOT NULL,email VARCHAR(190) NOT NULL,image VARCHAR(255) NULL,status ENUM('pending','active','inactive','rejected') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE SET NULL,INDEX(city,status)) ENGINE=InnoDB;
CREATE TABLE destinations (destination_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,city VARCHAR(100) NOT NULL,region VARCHAR(100) NOT NULL,description TEXT NOT NULL,attractions TEXT NULL,activities TEXT NULL,best_time_to_visit VARCHAR(150) NULL,estimated_budget DECIMAL(12,2) NOT NULL DEFAULT 0,image VARCHAR(255) NULL,status ENUM('active','inactive') DEFAULT 'active',popularity INT UNSIGNED DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX(name,city,region,status)) ENGINE=InnoDB;
CREATE TABLE packages (package_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,destination_id INT UNSIGNED NOT NULL,package_name VARCHAR(180) NOT NULL,description TEXT NOT NULL,duration_days TINYINT UNSIGNED NOT NULL,duration_nights TINYINT UNSIGNED NOT NULL,price_per_person DECIMAL(12,2) NOT NULL,max_travelers SMALLINT UNSIGNED NOT NULL,package_type VARCHAR(80) NOT NULL,included_services TEXT NULL,excluded_services TEXT NULL,itinerary TEXT NULL,image VARCHAR(255) NULL,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(destination_id) REFERENCES destinations(destination_id),INDEX(destination_id,status,price_per_person)) ENGINE=InnoDB;
CREATE TABLE rooms (room_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,hotel_id INT UNSIGNED NOT NULL,room_type VARCHAR(100) NOT NULL,description TEXT NULL,capacity TINYINT UNSIGNED NOT NULL,price_per_night DECIMAL(12,2) NOT NULL,total_rooms SMALLINT UNSIGNED NOT NULL,available_rooms SMALLINT UNSIGNED NOT NULL,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(hotel_id) REFERENCES hotels(hotel_id) ON DELETE CASCADE,INDEX(hotel_id,status)) ENGINE=InnoDB;
CREATE TABLE bookings (booking_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,customer_id INT UNSIGNED NOT NULL,package_id INT UNSIGNED NOT NULL,hotel_id INT UNSIGNED NULL,room_id INT UNSIGNED NULL,driver_id INT UNSIGNED NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,number_of_travelers SMALLINT UNSIGNED NOT NULL,number_of_rooms SMALLINT UNSIGNED DEFAULT 0,pickup_location VARCHAR(255) NULL,special_request TEXT NULL,package_total DECIMAL(12,2) NOT NULL,hotel_total DECIMAL(12,2) NOT NULL DEFAULT 0,driver_total DECIMAL(12,2) NOT NULL DEFAULT 0,total_amount DECIMAL(12,2) NOT NULL,booking_status ENUM('Pending','Confirmed','Cancelled','Completed') DEFAULT 'Pending',hotel_reservation_status ENUM('Not Required','Pending','Accepted','Rejected') DEFAULT 'Not Required',trip_status ENUM('Unassigned','Assigned','Accepted','On the Way','Picked Up','Completed','Cancelled') DEFAULT 'Unassigned',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES customers(customer_id),FOREIGN KEY(package_id) REFERENCES packages(package_id),FOREIGN KEY(hotel_id) REFERENCES hotels(hotel_id),FOREIGN KEY(room_id) REFERENCES rooms(room_id),FOREIGN KEY(driver_id) REFERENCES drivers(driver_id),INDEX(customer_id,booking_status),INDEX(hotel_id,hotel_reservation_status),INDEX(driver_id,start_date,end_date)) ENGINE=InnoDB;
CREATE TABLE payments (payment_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,booking_id INT UNSIGNED NOT NULL,amount DECIMAL(12,2) NOT NULL,payment_method ENUM('Cash','Bank Transfer','Mobile Payment') NOT NULL,transaction_reference VARCHAR(150) NULL,payment_status ENUM('Pending','Paid','Failed','Refunded') DEFAULT 'Pending',paid_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE,INDEX(booking_id,payment_status)) ENGINE=InnoDB;
CREATE TABLE contact_messages (message_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL,phone VARCHAR(40) NULL,subject VARCHAR(200) NOT NULL,message TEXT NOT NULL,is_read BOOLEAN DEFAULT FALSE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;

INSERT INTO destinations(name,city,region,description,attractions,activities,best_time_to_visit,estimated_budget,popularity) VALUES
('Bagan','Bagan','Mandalay Region','An ancient plain of thousands of temples, pagodas and quiet village lanes.','Ananda Temple, Shwezigon Pagoda, sunrise viewpoints','E-bike tours, balloon rides, temple walks','November to February',280000,95),
('Inle Lake','Nyaungshwe','Shan State','A tranquil highland lake known for floating gardens and Intha culture.','Floating gardens, Phaung Daw Oo, Indein','Boat tours, cycling, village visits','October to February',320000,90),
('Ngapali Beach','Thandwe','Rakhine State','A relaxed crescent of white sand and clear Bay of Bengal water.','Fishing villages, Pearl Island','Swimming, seafood, boat trips','November to April',380000,88),
('Yangon','Yangon','Yangon Region','Myanmar’s vibrant commercial capital, where colonial streets meet gilded pagodas.','Shwedagon, Bogyoke Market, Kandawgyi','City walks, food tours','November to February',180000,85),
('Mandalay','Mandalay','Mandalay Region','A cultural hub of monasteries, artisans and royal history.','Mandalay Hill, U Bein Bridge, Amarapura','Heritage tours, river cruise','November to February',250000,80),
('Hpa-An','Hpa-An','Kayin State','Karst peaks, sacred caves and peaceful countryside.','Saddan Cave, Kyauk Ka Lat','Caving, hiking, kayaking','November to February',220000,75),
('Ngwe Saung','Pathein','Ayeyarwady Region','A long, breezy beach escape within reach of Yangon.','Lovers Island, beach villages','Beach cycling, swimming','November to April',260000,70);
INSERT INTO packages(destination_id,package_name,description,duration_days,duration_nights,price_per_person,max_travelers,package_type,included_services,excluded_services,itinerary,status) VALUES
(1,'Bagan Cultural Discovery','A memorable temple and heritage journey through ancient Bagan.',3,2,185000,12,'Cultural','Guide, transport, entrance fees','Meals not listed, personal expenses','Day 1 arrival; Day 2 temple circuit; Day 3 sunrise and departure','active'),
(2,'Inle Lake Adventure','Discover floating gardens and lakeside communities.',3,2,220000,10,'Adventure','Boat tour, guide, transport','Flights, personal expenses','Day 1 Nyaungshwe; Day 2 lake exploration; Day 3 departure','active'),
(3,'Ngapali Beach Holiday','Three days of unhurried sea, sand and local flavours.',4,3,320000,8,'Beach','Airport transfer, island cruise','Meals, hotel','Day 1 arrival; Days 2–3 free beach time; Day 4 departure','active'),
(4,'Yangon City Essentials','An illuminating introduction to Yangon’s landmarks.',2,1,95000,15,'City','Guide, transport, entry fees','Meals','Day 1 downtown; Day 2 Shwedagon and departure','active'),
(5,'Mandalay Heritage Tour','Monasteries, crafts and sunset over the Irrawaddy.',3,2,175000,12,'Cultural','Guide, transport, entrance fees','Hotel, meals','Day 1 Mandalay; Day 2 Amarapura; Day 3 departure','active');
INSERT INTO hotels(hotel_name,description,address,city,phone,email,status) VALUES
('Golden Palace Hotel','A comfortable heritage-inspired stay close to Bagan temples.','Old Bagan Road','Bagan','+95 9 401 111 222','stay@goldenpalace.test','active'),
('Lake View Retreat','Peaceful lakeside rooms with attentive local hospitality.','Yone Gyi Road','Nyaungshwe','+95 9 401 333 444','stay@lakeview.test','active'),
('Bay Breeze Resort','A sunny beach retreat with spacious family accommodation.','Linn Thar Village','Ngapali','+95 9 401 555 666','stay@baybreeze.test','active');
INSERT INTO rooms(hotel_id,room_type,description,capacity,price_per_night,total_rooms,available_rooms,status) VALUES
(1,'Standard Room','Comfortable double or twin room.',2,65000,12,12,'active'),(1,'Deluxe Room','Spacious room with garden view.',3,95000,8,8,'active'),(1,'Family Room','Two-bedroom suite for families.',5,145000,4,4,'active'),
(2,'Standard Room','Bright room with breakfast included.',2,70000,10,10,'active'),(2,'Deluxe Lake View','Lake-facing room with balcony.',2,120000,7,7,'active'),(2,'Family Room','Generous room for group stays.',4,155000,3,3,'active'),
(3,'Garden Room','Quiet garden-facing room.',2,85000,14,14,'active'),(3,'Ocean Deluxe','Sea-view room with private balcony.',2,145000,8,8,'active'),(3,'Family Villa','Beach villa for families.',5,220000,5,5,'active');
-- Initial admin: generate a secure hash with PHP then replace PLACEHOLDER_HASH before import:
-- php -r "echo password_hash('your-new-password', PASSWORD_DEFAULT);"
-- INSERT INTO users(name,email,password_hash,role,status) VALUES ('System Admin','admin@example.com','PASTE_HASH_HERE','admin','active');
USE tourism_db;

ALTER TABLE users
  ADD COLUMN must_change_password TINYINT(1) NOT NULL DEFAULT 0 AFTER status;

-- If you have already run this migration, the statement fails with
-- "Duplicate column name" - that is harmless; skip this file.